### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by turbo124** [AXN-Informatique/laravel-pk-int-to-bigint#4]
any chance to bump dependencies to support Laravel 9 please.

**Comment by forxer** [comment]
Yes I thought we had already done that. I hope this won't introduce regression (we don't have any tests)

**Comment by forxer** [comment]
Attempt on version 1.3.0 but I don't have any available to test.

All our latest applications already use bigint as primary keys...

**Comment by turbo124** [comment]
Just to confirm, should this script upgrade the PK on the primary tables themselves?

**Comment by forxer** [comment]
Yes, primary keys and related foreign keys.
