### ISSUE TITLE
Issue with Primary Key

### ISSUE THREAD

**Issue by XBS-Nathan** [AXN-Informatique/laravel-pk-int-to-bigint#5]
Having an issue with primary keys, using the latest version of laravel 9.17. It appears that when it getting the primary keys from the table, the item that is return is an object rather then just it key.

vendor/axn/laravel-pk-int-to-bigint/src/Transformer.php:139
` $tableKeysColumnsNames = $table->getPrimaryKeyColumns();`

Here a screenshot of xdebug showing the contents of that array. So when it comes checking the column name if it exists in that array, it fails that check and skips the primary key. Any fixes going around for this?

![image](https://user-images.githubusercontent.com/2473531/184149943-4e50ba8d-dc2c-45e8-a8b0-b32826f0c501.png)

**Comment by forxer** [comment]
I think this is a problem with DBAL 3.5; hoping that version 1.3.1 fixes the problem.

**Comment by forxer** [comment]
I haven't had an answer for several months, so I'm closing this issue.
